# Generated by Django 3.0.3 on 2020-02-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=60)),
                ('port', models.CharField(max_length=60)),
                ('data', models.CharField(max_length=60)),
                ('codigocet', models.CharField(max_length=60)),
                ('velocidade', models.CharField(max_length=60)),
            ],
        ),
    ]
