# Generated by Django 3.0.3 on 2020-02-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='OCR',
        ),
    ]
