# Generated by Django 3.0.3 on 2020-02-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200214_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocr',
            old_name='port',
            new_name='porte',
        ),
    ]
